//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravailBDPart4
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Resultat
    {
        public int Id_competition { get; set; }
        public int Id_Nageur { get; set; }
        public Nullable<int> Position { get; set; }
    
        public virtual tbl_Competition tbl_Competition { get; set; }
        public virtual tbl_Nageur tbl_Nageur { get; set; }
    }
}
