//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravailBDPart4
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Nageur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Nageur()
        {
            this.tbl_Resultat = new HashSet<tbl_Resultat>();
        }
    
        public int id_nageur { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string Genre { get; set; }
        public string Adresse_Email { get; set; }
        public Nullable<int> Id_Categorie_Nageur { get; set; }
    
        public virtual tbl_Categorie_Nageur tbl_Categorie_Nageur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Resultat> tbl_Resultat { get; set; }
    }
}
