//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravailBDPart4
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Competition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Competition()
        {
            this.tbl_Resultat = new HashSet<tbl_Resultat>();
        }
    
        public int ID { get; set; }
        public string Nom { get; set; }
        public string Description { get; set; }
        public decimal Distance { get; set; }
        public int Id_Categori_Compet { get; set; }
        public byte[] versionHolder { get; set; }
    
        public virtual tbl_Categori_Compet tbl_Categori_Compet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Resultat> tbl_Resultat { get; set; }
    }
}
